# Generated by Django 4.1 on 2022-09-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="comfood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField()),
                ("name", models.TextField()),
                ("gramms", models.IntegerField()),
                ("proteins", models.FloatField()),
                ("fats", models.FloatField()),
                ("carbohydrates", models.FloatField()),
                ("calories", models.FloatField()),
                ("category", models.TextField()),
            ],
        ),
    ]
